language: android
jdk: oraceljdk7
android:
  components:
	# The BuildTools version used by your project
	- build-tools-23.0.2
	# The SDK version used to compile your project
	- android-23
	# Additional components
	- extra-android-m2repository
	# Specify at least one system image,
	# if you need to run emulator(s) during your tests
	- sys-img-armeabi-v7a-android-19
	- sys-img-x86-android-19
  licenses:
	  - android-sdk-licence-.+
