language: android
env:
  global:
    - MALLOC_ARENA_MAX=2

sudo: required
jdk:
  - oraclejdk8
android:
  components:
    - build-tools-24.0.2
    - android-24
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

script:
- "./gradlew :app:assembleDebug"
