language: android
android:
  components:
    - build-tools-19.0.0
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-19
  licenses:
    - android-sdk-licence-.+