language: android
env:
  matrix:
    - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-19.0.0
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19
  licenses:
    - android-sdk-licence-.+