language: android
env:
  matrix:
    - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a

sudo: false

android:
  components:
    - build-tools-24.0.2
    - android-24
    #- extra-android-m2repository
    #- extra-android-support
    - sys-img-armeabi-v7a-android-19
  licenses:
    - android-sdk-licence-.+

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script: ./gradlew assembleRelease